[ERROR] There is a conflict between multiple exceptions for assigning the same variable.
[ERROR] 
[ERROR] This justification is true:
[ERROR]  --> test_default/bad/conflict.catala
[ERROR]   | 
[ERROR] 9 |   def x [|true|] := 0
[ERROR]   |           ^^^^
[ERROR]   + Article
[ERROR] 
[ERROR] This justification is true:
[ERROR]  --> test_default/bad/conflict.catala
[ERROR]   | 
[ERROR] 8 |   def x [|true|] := 1
[ERROR]   |           ^^^^
[ERROR]   + Article
